language: python

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
python:
    # - 2.6
    - 2.7
    # - 3.3
    # - 3.4
    # This is just for "egg_info".  All other builds are explicitly given in the matrix
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.9
        - SCIPY_VERSION=0.14
        - ASTROPY_VERSION=stable
        - SPHINX_VERSION=1.3
        - CONDA_INSTALL='conda install -c astropy-ci-extras --yes'
        - PIP_INSTALL='pip install'
        - OPTIONAL_DEPS=false
        - MAIN_CMD='python setup.py'
    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:

        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx'
          # OPTIONAL_DEPS needed because the plot_directive in sphinx needs them
          # -w is an astropy extension

        # Do a bdist_egg compile.  This will catch things like syntax errors
        # without needing to do a full python setup.py test
        - python: 2.7
          env: SETUP_CMD='bdist_egg'

        # Try all python versions with the latest numpy
        - python: 2.7
          env: SETUP_CMD='test'
        # - python: 3.3
        #   env: SETUP_CMD='test --open-files'
        # - python: 3.4
        #   env: SETUP_CMD='test --open-files'

        # Now try do scipy on 2.7 and an appropriate 3.x build (with latest numpy)
        # We also note the code coverage on Python 2.7.
        # - python: 2.7
        #   env: SETUP_CMD='test --coverage'  OPTIONAL_DEPS=true LC_CTYPE=C.ascii LC_ALL=C.ascii
        # - python: 3.4
        #   env: SETUP_CMD='test'  OPTIONAL_DEPS=true LC_CTYPE=C.ascii LC_ALL=C.ascii

        # Try older numpy versions
        # - python: 2.7
        #   env: NUMPY_VERSION=1.8 SETUP_CMD='test'
        # - python: 2.7
        #   env: NUMPY_VERSION=1.7 SETUP_CMD='test'
        # - python: 2.7
        #   env: NUMPY_VERSION=1.6 SETUP_CMD='test'

        # Do a PEP8 test
        # - python: 2.7
        #   env: MAIN_CMD='pep8 astropy --count' SETUP_CMD=''

install:
    - source .continuous-integration/travis/setup_environment_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    # - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='astropy/tests/coveragerc'; fi
